# cat config/database.yml
# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
production:
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  database: d9tupv30f674g0
  host: ec2-54-83-199-54.compute-1.amazonaws.com
  username: jbjbqbyqjusvmh
  password: 70PJIlZRHxxARB41NDtcjMwG6n
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  database: d9tupv30f674g0
  host: ec2-54-83-199-54.compute-1.amazonaws.com
  username: jbjbqbyqjusvmh
  password: 70PJIlZRHxxARB41NDtcjMwG6n
  timeout: 5000